-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, ROUND(30 * c.DAILY_FEE *(1 - (d.DISCOUNT_RATE / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  AS d
ON c.CAR_TYPE = d.CAR_TYPE
AND d.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN('SUV', '세단')
AND NOT EXISTS
(
 SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
    WHERE c.CAR_ID = h.CAR_ID
    AND h.END_DATE >= '2022-11-01' AND h.START_DATE <= '2022-11-30'
)
GROUP BY FEE HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC