-- 코드를 입력하세요
SELECT MONTH(START_DATE) as MONTH, CAR_ID, count(*) as RECORDS
from CAR_RENTAL_COMPANY_RENTAL_HISTORY h
where START_DATE >= '2022-08-01' AND
START_DATE < '2022-11-01' AND CAR_ID In
(
select CAR_ID from CAR_RENTAL_COMPANY_RENTAL_HISTORY
    where START_DATE >= '2022-08-01' AND
START_DATE < '2022-11-01'
    group by CAR_ID having count(*) >= 5
)

group by CAR_ID, MONTH(START_DATE)
order by MONTH(START_DATE) ASC, CAR_ID DESC